# add all routes
from .user import *
from .game import *
from .word import *
from .stat import *
from .account_stat import *
from .bank import *
from .achievement_type import *
from .score import *
from .game_achievements import *
from .game_assets import *
from .achievement import *
from .account_achievements import *
